const REGISTER_LOADING = 'REGISTER_LOADING';
const REGISTER_FAILED = 'REGISTER_FAILED';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_REQUEST = 'REGISTER_REQUEST';

export default {
  REGISTER_LOADING,
  REGISTER_FAILED,
  REGISTER_SUCCESS,
  REGISTER_REQUEST
};
