const USER_REGISTER_LOADING = 'USER_REGISTER_LOADING';
const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';

export default {
  USER_REGISTER_LOADING,
  USER_REGISTER_FAILED,
  USER_REGISTER_SUCCESS,
  USER_REGISTER_REQUEST
};
